language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    # Tools appears twice on purpose as it’s required to get the newest Android SDK tools
    - tools

    # The BuildTools version used by this project
    - build-tools-29.0.0
    # The SDK version used to compile this project
    - android-28

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - openjdk8
before_install:
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - "./gradlew clean build library:test"
